ShopApp.WEBUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ShopApp.Entity;
using ShopApp.WEBUI.Identity;
using ShopApp.WEBUI.Models;

namespace ShopApp.WEBUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private UserManager<User> _userManager;
        private IOrderService _orderService;


        public CartController(IOrderService orderService, ICartService cartService, UserManager<User> userManager)
        {
            _orderService = orderService;
            _cartService = cartService;
            _userManager = userManager;    
        }
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            return View(new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity

                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int productId,int quantity)
        {
            var userId = _userManager.GetUserId(User);

            _cartService.AddToCart(userId,productId,quantity);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            var userId = _userManager.GetUserId(User);

            _cartService.DeleteFromCart(userId, productId);

            return RedirectToAction("Index");
        }
        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity

                }).ToList()
            };

            return View(orderModel);
        }
        [HttpPost]
        public IActionResult CheckOut(OrderModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserId(userId);

                model.CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = (double)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };

                var payment = PaymentProccess(model);

                if (payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(model.CartModel.CartId);
                    return View("Success");
                }
                else
                {
                    var msg = new AlertMessage()
                    {
                        Message = $"{payment.ErrorMessage}",
                        AlertType = "danger"
                    };

                    TempData["message"] = JsonConvert.SerializeObject(msg);
                }
            }
            return View(model);
        }

        [Authorize(Roles ="admin")]
        public IActionResult GetAdminOrders()
        {
            var userId = _userManager.GetUserId(User);
            var orders = _orderService.GetOrders(null);

            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;
            foreach (var order in orders)
            {
                orderModel = new OrderListModel();

                orderModel.OrderId = order.Id;
                orderModel.OrderNumber = order.OrderNumber;
                orderModel.OrderDate = order.OrderDate;
                orderModel.Phone = order.Phone;
                orderModel.FirstName = order.FirstName;
                orderModel.LastName = order.LastName;
                orderModel.Email = order.Email;
                orderModel.Address = order.Address;
                orderModel.City = order.City;
                orderModel.OrderState = order.OrderState;
                orderModel.PaymentType = order.PaymentType;

                orderModel.OrderItems = order.OrderItems.Select(i => new OrderItemModel()
                {
                    OrderItemId = i.Id,
                    Name = i.Product.Name,
                    Price = (double)i.Price,
                    Quantity = i.Quantity,
                    ImageUrl = i.Product.ImageUrl
                }).ToList();

                orderListModel.Add(orderModel);
            }


            return View("Orders", orderListModel);
        }


        public IActionResult GetOrders()
        {
            var userId = _userManager.GetUserId(User);
            var orders = _orderService.GetOrders(userId);

            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;
            foreach (var order in orders)
            {
                orderModel = new OrderListModel();

                orderModel.OrderId = order.Id;
                orderModel.OrderNumber = order.OrderNumber;
                orderModel.OrderDate = order.OrderDate;
                orderModel.Phone = order.Phone;
                orderModel.FirstName = order.FirstName;
                orderModel.LastName = order.LastName;
                orderModel.Email = order.Email;
                orderModel.Address = order.Address;
                orderModel.City = order.City;
                orderModel.OrderState = order.OrderState;
                orderModel.PaymentType = order.PaymentType;

                orderModel.OrderItems = order.OrderItems.Select(i => new OrderItemModel()
                {
                    OrderItemId = i.Id,
                    Name = i.Product.Name,
                    Price = (double)i.Price,
                    Quantity = i.Quantity,
                    ImageUrl = i.Product.ImageUrl
                }).ToList();

                orderListModel.Add(orderModel);
            }


            return View("Orders", orderListModel);
        }


        private void ClearCart(int cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            var order = new Order();

            order.OrderNumber = new Random().Next(111111, 999999).ToString();
            order.OrderState = EnumOrderState.completed;
            order.PaymentType = EnumPaymentType.CreditCard;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.UserId = userId;
            order.Address = model.Address;
            order.Phone = model.Phone;
            order.Email = model.Email;
            order.City = model.City;
            order.Note = model.Note;

            order.OrderItems = new List<ShopApp.Entity.OrderItem>();

            foreach (var item in model.CartModel.CartItems)
            {
                var orderItem = new ShopApp.Entity.OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId
                };
                order.OrderItems.Add(orderItem);
            }
            _orderService.Create(order);
        }

        private Payment PaymentProccess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-3aMgaT0kOANKoe3OiFt49YtSKNPfgNoa";
            options.SecretKey = "sandbox-687wRAIsY4mquOsdfZ75bR2LxXHU7lsn";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = new Random().Next(111111111, 999999999).ToString();
            request.Price = model.CartModel.TotalPrice().ToString();
            request.PaidPrice = model.CartModel.TotalPrice().ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = "B67832";
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvc;
            paymentCard.RegisterCard = 0;

ShopApp.WEBUI/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Business.Abstract;
using ShopApp.Entity;
using ShopApp.WEBUI.Models;

namespace ShopApp.WEBUI.Controllers
{
    public class ShopController : Controller
    {
       
        private IProductService _productService;

        public ShopController(IProductService productService)
        {
            this._productService = productService;
        }

        public IActionResult List(string category,int page=1)
        {
            const int pageSize = 6;
            var productViewModel = new ProductListViewModel()
            {
                PageInfo=new PageInfo()
                {
                    TotalItems=_productService.GetCountByCategory(category),
                    CurrentPage=page,
                    ItemsPerPage=pageSize,
                    CurrentCategory=category
                },

                Products = _productService.GetProductsByCategory(category,page,pageSize)
            };

            return View(productViewModel);
        }


        // GET: Shop/Details/5
        public IActionResult Details(string url)
        {
            if (url == null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails(url);

            if (product == null)
            {
                return NotFound();
            }
            return View(new ProductDetailModel
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList()
            });
        }

        public IActionResult Search(string q)
        {
         
            var productViewModel = new ProductListViewModel()
            {
                Products = _productService.GetSearchResult(q)
            };

            return View(productViewModel);
        }




    }
}

ShopApp.WEBUI/ViewComponents/CategoriesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAcces.Abstract;
using Microsoft.AspNetCore.Mvc;
using Business.Abstract;
using ShopApp.Entity;

namespace ShopApp.WEBUI.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoriesViewComponent(ICategoryService categoryService)
        {
            this._categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["category"] != null)
                ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(_categoryService.GetAll());
        }
    }

      
    }

ShopApp.WEBUI/Views/Shop/Details.cshtml
@model ShopApp.WEBUI.Models.ProductDetailModel 

    <div class="row">
        <div class="col-md-3">
            <img src="~/img/@Model.Product.ImageUrl" class="img-fluid">
        </div>
        <div class="col-md-9">
            <h1 class="mb-3">
                @Model.Product.Name</h5> <hr>

            @foreach (var item in Model.Categories)
            {
                <a asp-controller="shop" asp-action="list" asp-route-category="@item.Url" class="btn btn-link p-0 mb-3">@item.Name</a>
            }

            <div class="mb-3">
                <h4 class="text-primary mb-3">
                    <i class="fas fa-lira-sign"></i>@Model.Product.Price
                </h4>
                @if (!User.IsInRole("admin"))
                {
                    <form asp-controller="Cart" asp-action="AddToCart" method="POST" class="form-inline">
                        <input type="hidden" name="productId" value="@Model.Product.ProductId">
                        <div class="input-group mb-3">
                            <input type="number" name="quantity" class="form-control" value="1" min="1" step="1" style="width: 100px;">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-cart-plus"></i>Add to Cart
                                </button>
                            </div>
                        </div>

                    </form>

                }
                @if (User.IsInRole("admin"))
                {
                    <form asp-controller="Home" asp-action="Index" method="POST" class="form-inline">
                        <input type="hidden" name="productId" value="@Model.Product.ProductId">
                        <div class="input-group mb-3">
                            <input type="number" name="quantity" class="form-control" value="1" min="1" step="1" style="width: 100px;">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-cart-plus"></i>Add to Cart
                                </button>
                            </div>
                        </div>

                    </form>

                }

                </h6>
            </div>
    </div>
    <div class="row">
        <div class="col-md-12 p-5">
            <p class="p-3">@Html.Raw(Model.Product.Description)</p>
        </div>
    </div>

ShopApp.WEBUI/Views/Shop/List.cshtml
@model ShopApp.WEBUI.Models.ProductListViewModel
@{
    ViewData["Title"] = "List";
}

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
        @await Html.PartialAsync("_search")

    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in Model.Products)
            {
                <div class="col-md-4">
                    @await Html.PartialAsync("_showproduct", product)
                </div>
            }
            @if (Model.Products.Count == 0)
            {
                <div class="col-md-12">
                    <div class="alert alert-danger">
                        Ürün Yok :(
                    </div>
                </div>
            }
        </div>          <div class="row">
            <div class="col">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">

                        @for (int i = 0; i < Model.PageInfo.TotalPages(); i++)
                        {
                            @if (String.IsNullOrEmpty(Model.PageInfo.CurrentCategory))
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1?"active":"")">
                                    <a class="page-link" href="/products?page=@(i+1)">
                                        @(i+1)
                                    </a>
                                </li>

                            }
                            else
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1?"active":"")">
                                    <a class="page-link" href="/products/@Model.PageInfo.CurrentCategory?page=@(i+1)">
                                        @(i+1)
                                    </a>
                                </li>

                            }


                        }


                    </ul>
                </nav>
            </div>
        </div>

    </div>
    
  
</div>



@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
}

ShopApp.WEBUI/Views/Shop/Search.cshtml
@model ShopApp.WEBUI.Models.ProductListViewModel
@{
    ViewData["Title"] = "List";
}

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
        @await Html.PartialAsync("_search")

    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in Model.Products)
            {
                <div class="col-md-4">
                    @await Html.PartialAsync("_showproduct", product)
                </div>
            }
            @if (Model.Products.Count == 0)
            {
                <div class="col-md-12">
                    <div class="alert alert-danger">
                        Ürün Yok :(
                    </div>
                </div>
            }
        </div>   
        
 

    </div>


</div>

@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
}